Algoritmo "Calcular o volume de uma caixa"
// Disciplina  : [Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   : Solicitar o comprimento, altura e largura para revelar o volume da caixa
// Autor(a)    : Thamires Campos
// Data atual  : 12/09/2022
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo